name: example
description: A new Dart project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  logster:
    path: ../

dev_dependencies:
  analysis_options: ^2.0.1
