name: logs
description: An extensible logger for applications, packages and plugins.
version: 0.0.1

homepage: https://G1Joshi.dev/docs/logs/about/
repository: https://github.com/G1J0SHI/logs

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  analysis_options: ^2.0.1
