name: logster
description: An extensible logger for applications, packages and plugins.
version: 0.1.0

homepage: https://G1Joshi.dev/docs/logster/about/
repository: https://github.com/G1J0SHI/logster

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  analysis_options: ^2.0.1
